### ISSUE TITLE
figure handles in matlab2014b

### ISSUE THREAD

**Issue by JWinawer** [kendrickkay/knkutils#1]
In Matlab2014b (8.4) and beyond, figure handles are a class rather than a number. This is rather annoying. Among other things, it breaks printnice, which has the line:

70 filename = sprintf([prefix '.png'],fig);

If fig is a class rather than a number, this causes an error. One fix that will maintain backwards compatibility is to add this line to prrintnice:

  if isnumeric(fig), fignum = fig; else fignum = get(fig, 'number'); end

Then, where a figure handle is needed, you leave fig, and where a number is needed, you use fignum instead of fig. The only places fignum is needed are lines 70 and 77:

70     filename = sprintf([prefix '.eps'],fig); =>     filename = sprintf([prefix '.png'],fignum);
77     filename = sprintf([prefix '.png'],fig); =>     filename = sprintf([prefix '.png'],fignum);

-Jon

**Comment by kendrickkay** [comment]
fixed.
