### ISSUE TITLE
Error in resizing stumulus for pRF experiment.

### ISSUE THREAD

**Issue by GongZhengxin** [kendrickkay/knkutils#5]
In **runretinotopy.m**, I set the **dres = [578, 578]** to resize the presentation.
And I remain all the other parameters the same as default.

resampling the stimuli; this may take a while.imresizememory: saving images to disk...done.
imresizememory: processing images....................done.
imresizememory: saving images to disk...done.
imresizememory: processing images.**CANNOT CONDUCT ASSIGNMENT, THE  SIZE OF LEFT IS 578x578, THE SIZE OF RIGHT IS 578x578x2580** 

**ERROR: imresizememory (line 57)
      f(:,:,p) = im;

ERROR: showmulticlass (line 705)
      maskimages = imresizememory(imtemp);

ERROR: runretinotopy (line 60)
  showmulticlass(filename,offset,movieflip,frameduration,fixationinfo,fixationsize,tfun, ...**

**Comment by GongZhengxin** [comment]
I changed my strategy to use **scfator** for presenation and it works well.
But I am still curious about the above question. I tried to use another laptop (window too) and run it in Matlab R2018 & R2012, the error became "out of memory."  which I met when the memory of my computer was 32G and disappeared when I increased memory to 48G.

**Comment by kendrickkay** [comment]
The first bug you noticed has been fixed.  (I checked in a change to imresizememory.m).  Thanks for finding this crash and reporting it.

Regarding the out of memory issue, it could just be that the stimulus images are too big to fit into the computer with less RAM ?
